### ISSUE TITLE
Tap to refresh always showing

### ISSUE THREAD

**Issue by edwingsm** [johannilsson/android-pulltorefresh#69]
Tap to refresh Textview is always showing when listview is loaded

**Comment by cesvi87** [comment]
Same bug. I've got 3 listviews. The first one works well, but the other two listviews show "Tap to refresh". (The code is the same for the 3 items)

**Comment by johannilsson** [comment]
This is not a bug, this is by design. There's a separate [branch](https://github.com/johannilsson/android-pulltorefresh/tree/scrollfix_for_short_list) which aims to implement an alternative approach that removes the Tap to refresh view. @chrisbanes also have a more [updated version](https://github.com/chrisbanes/Android-PullToRefresh) of an Pull to Refresh implementation that might be a better fit for your project.

**Comment by johannilsson** [comment]
Link to the none deprecated version, https://github.com/chrisbanes/ActionBar-PullToRefresh
